name: symbrim-tutorials
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.14
  - pip
  - notebook
  - requests
  - scikits.odes
  - matplotlib
  - symmeplot
  - pip:
      - git+https://github.com/moorepants/BicycleParameters.git
      - git+https://github.com/mechmotum/symbrim.git
