name: brim-tutorials
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.12
  - pip
  - notebook
  - requests
  - scikits.odes
  - pip:
      - git+https://github.com/moorepants/BicycleParameters.git
      - git+https://github.com/TJStienstra/brim.git
      - git+https://github.com/TJStienstra/symmeplot.git
